### ISSUE TITLE
As an Administrator, I want there to be a Pending Review tab in the moderation page that allows me to view all reported content so that I can conveniently moderate content on a single page.

### ISSUE THREAD

**Issue by Retalak** [CEN-3031-2023-7D/emerald-project13-7d#2]
- [x] If focused on the Resolved tab, clicking on the Pending Review tab at the top of the page switches the screen to the Pending Review tab.

- [x] Reported posts/comments are listed under this tab.

- [x] For each post/comment, the username, # of reports, # of views, and report ratio are all visible.

- [x] For each post/comment, there are Approve and Reject buttons.

- [x] For each post/comment, clicking on the post/comment redirects the Administrator to the post’s page in the gallery.

**Comment by dfserrano1** [comment]
Instead of me completing the entire Pending Review tab as originally planned, Annabela and I have adjusted our tasks. I'm working on the incident summary box and the tab switcher for both tabs, and she's working on the incident tables for both tables. We haven't integrated our work together yet.

The tab switcher is fully functional and switches tabs depending on what tab was clicked. The incident summary box is also functional. It displays the data and changes depending on whether the incident is a post/comment and whether the Pending Review or Resolved tab was clicked.

To test my work, I ensured that the ViewIncident component would render the expected data depending on whether true or false were passed to its two props. For now, incident data is hardcoded into the component, but there is also functionality in-place to throw exceptions if the selected incident has unexpected data (although this is now commented out for testing purposes).

Next steps:
- Integrate my work with Annabela's for both tabs
- Render Parker's action buttons in the incident summary box
- Create the "open" button to open the selected incident in the incident summary box
- Add an autohidden field to the incident summary (as discussed on 11/9)

Wireframe link: https://www.figma.com/file/SoaDGtPTieYnz9mBVONgWQ/Project-13-Moderation?type=design&node-id=0%3A1&mode=design&t=U4FsTA1X62sSrpli-1
